### PR TITLE
Feature/add specific storage configuration and tests

### PR DESCRIPTION
**Pull request by ben-vaughan-nttd**
* add DB storage management

### CODE REVIEW

**Review by philip-morgan-nttd — APPROVED** [review]
on the go - unsure if the post deployment tests really connects to MySQL created.
Ideally it should run a trival SQL query like "SELECT 1" and get expected response.

OUT of scope of this PR

**Review by bryce-lynn-nttd — COMMENTED** [review]
The specific_storage example doesn't actually set the storage.  The variable isn't passed into the root module.  I ran the example and checked the portal, and it shows dynamic storage.

**Comment by bryce-lynn-nttd** [comment]
Since I originally skipped adding the storage thing, I have a fix here in this branch: fix/storage_var.  You can merge or cherry-pick from there.

**Comment by kevin11-allen-nttd** [comment]
> on the go - unsure if the post deployment tests really connects to MySQL created. Ideally it should run a trival SQL query like "SELECT 1" and get expected response.
> 
> OUT of scope of this PR

I tried doing this with postgres, but I would have needed to create another primitive to create firewall rules, since even when public access is enabled, it only allows IPs on the firewall list

I stopped short of this since I don't actually intend on running the database public

**Review by kevin11-allen-nttd — APPROVED** [review]

**Review by bryce-lynn-nttd — APPROVED** [review]

**Pull request merged**
